version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/data:/usr/src/app/data
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3002/api